web:
  image: nginx:latest
  ports:
    - 80:80
  volumes:
    - ./web:/var/www/html
    - ./config/vhost.conf:/etc/nginx/conf.d/vhost.conf
  links:
    - php
php:
  build: ./config/php
  volumes:
    - ./web:/var/www/html
    - ./config/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
  links:
    - db
  entrypoint: /var/www/html/entrypoint.sh
db:
  image: mysql:latest
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=todo
generator:
  build: ./config/php
  volumes:
    - ./genwork:/app
  working_dir: /app
  links:
    - beanstalkd
  command: php generator.php
worker:
  build: ./config/php
  volumes:
    - ./genwork:/app
  working_dir: /app
  links:
    - beanstalkd
    - db
  command: php worker.php
beanstalkd:
  image: schickling/beanstalkd:latest
